import { Strategies } from "@/types/game";

export const strategies: Strategies = {
  philosophical: [
    "Écoute le bruit de fond",
    "Que se passerait-il si c'était beaucoup plus lent ?",
    "Suis la tension",
    "Crée de la musique pour une pièce vide",
    "À quoi ressemblerait ce son sous l'eau ?",
    "Trouve l'espace entre les déclencheurs",
    "Imagine ce son dans 100 ans",
    "Le module le plus silencieux est le plus important",
    "Commence par la fin",
    "Et si c'était de la musique de danse ?",
    "Écoute comme si tu découvrais le son pour la première fois",
    "Quel temps fait-il dans ce patch ?",
    "Transforme le bruit en musique",
    "Fais-le sonner comme un souvenir",
    "Crée le son de l'attente",
    "À quoi ressemble ce patch à l'aube ?",
    "Crée pour une pièce vide",
    "Trouve l'espace entre les événements",
    "Imagine ce son dans cent ans",
    "Le plus discret devient essentiel",
    "Commence par la fin",
    "Et si c'était une danse ?",
    "Écoute comme si c'était la première fois",
    "Quelle température a ce son ?",
    "Le bruit devient musique",
    "Fais sonner un souvenir",
    "Le temps n'est qu'une illusion",
    "La lenteur révèle",
    "Comment sonne l'invisible ?",
    "Où commence le son ?",
  ],
  soundscape: [
    "Une usine qui respire la nuit",
    "Le métal sous la pluie",
    "Des turbines dans la brume",
    "L'orage entre les antennes",
    "Le vent dans les câbles",
    "Les machines sous la glace",
    "Un signal radio dans le désert",
    "La résonance d'une cathédrale vide",
    "Des engrenages sous l'eau",
    "Le dernier train du soir",
    "Les ondes entre les murs",
    "Le souffle des générateurs",
    "Le métal qui se tord",
    "La ville qui se réveille",
    "Un transformateur sous la neige",
    "L'écho dans les tuyaux",
    "Les interférences du rêve",
    "Le bruit blanc de l'aube",
    "La tension avant l'orage",
    "Le murmure des néons",
  ],
  compositional: [
    "Construis les espaces entre les sons",
    "Les cinq premières secondes sont toute la pièce",
    "Que se passerait-il si ça durait une heure ?",
    "Crée le son de l'attente",
    "Rends-le moins musical",
    "Le rythme est au mauvais endroit",
    "Trouve l'harmonie dans le chaos",
    "Compose avec les accidents",
    "La première idée est la meilleure",
    "Fais le contraire de ce que tu ferais normalement",
    "Crée une mélodie sans oscillateur",
    "Le rythme vient d'ailleurs",
    "Tout doit être en mouvement constant",
    "N'utilise que des sons courts",
    "Moins de modules, plus de modulation",
    "Laisse le hasard décider",
    "Fais quelque chose d'inutilement complexe",
    "La boucle devient infinie",
  ],
  experimental: [
    "Patch à l'aveugle",
    "Utilise uniquement des modules que tu connais mal",
    "Crée un instrument impossible",
    "Fais sonner l'électricité",
    "Le patch doit se jouer tout seul",
    "Transforme le son en image",
    "Fais quelque chose d'incorrect",
    "Utilise le système de façon non prévue",
    "Créé un nouveau langage",
    "Rends l'instable stable",
    "Trouve la beauté dans le laid",
    "Fais de la musique sans son",
    "Désobéis aux règles du patch",
    "Crée un système vivant",
    "Le hasard est la seule règle",
    "Utilise ce qui ne devrait pas marcher",
    "Fais l'opposé de la dernière fois",
    "Patch sans but",
    "Laisse le système se détruire",
  ],
  performance: [
    "Trouve le geste parfait",
    "Le silence fait partie de la performance",
    "Transforme l'accident en intention",
    "L'espace entre les gestes est musical",
    "Un seul geste doit tout changer",
    "Le patch joue avec toi",
    "Crée une tension invisible",
    "Le temps est élastique",
    "La lenteur révèle de nouveaux sons",
    "L'intention avant le mouvement",
    "Laisse le système te surprendre",
    "Le contrôle est une illusion",
    "L'imperfection est nécessaire",
    "Chaque geste a une conséquence",
    "L'attente crée la musique",
    "Le hasard guide tes mains",
    "L'erreur est une direction",
    "L'écoute guide le geste",
  ],
};
